//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalsApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Registration
    {
        public int CarID_PK { get; set; }
        public string CarName { get; set; }
        public string CarNumber { get; set; }
        public Nullable<int> HourlyRate { get; set; }
        public string CarImagePath { get; set; }
        public bool IsRented { get; set; }
        public bool IsReturned { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
